InventoryTracker/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
#from django.contrib.auth import views
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from InventoryTracker import settings

admin.autodiscover()

urlpatterns = [
               url(r'^tracker/', include('tracker.urls')),
               url(r'^admin/', admin.site.urls),
               url('^', include('django.contrib.auth.urls')),
               ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += staticfiles_urlpatterns()

if settings.DEBUG:
    urlpatterns += patterns('', url(r'^site_media/media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT, 'show_indexes': True}),)

handler403 = 'tracker.views.custom_permission_denied_view'

tracker/urls.py
from django.conf.urls import include, url
from . import views
from django.contrib.auth import views as auth_views

app_name = 'tracker'
urlpatterns = [
               # ex: /tracker/
               url(r'^$', views.index, name='index'),
               
               # ex: /tracker/gum%20ball/product_inventory
               url(r'^(?P<product_name>[\w\s]+)/product_inventory/$', views.product_inventory, name='product_inventory'),
               # ex: /tracker/view_products lists current products
               url(r'^view_products/$', views.view_products, name='view_products'),
               # ex: /tracker/add_product brings up add new product form view
               url(r'^add_product/$', views.add_product, name='add_product'),
               # ex: /tracker/new_product accessible only through form submission from add_product.html
               url(r'^new_product/$', views.new_product, name='new_product'),
               # ex: /tracker/product_details/104 add product form, displays all details about existing products
               url(r'^product_details/(?P<sm_lot_number>\d+)$', views.product_details, name='product_details'),
               # ex: /tracker/delete_product accessible only through form submission from add_product.html
               url(r'^delete_product/(?P<sm_lot_number>\d+)$', views.delete_product, name='delete_product'),
               
               # ex: /tracker/add_inventory
               url(r'^add_inventory/$', views.add_inventory, name='add_inventory'),
               # ex: /tracker/new_inventory accessible only through form submission from add_inventory.html
               url(r'^new_inventory/$', views.new_inventory, name='new_inventory'),
               # ex: /tracker/update_inventory accessible only through form submission from product_inventory.html
               url(r'^update_inventory/(?P<counter>\d+)$', views.update_inventory, name='update_inventory'),
               # ex: /tracker/update_inventory_label accessible only through form submission from product_inventory.html
               url(r'^update_inventory_label/(?P<counter>\d+)$', views.update_inventory_label, name='update_inventory_label'),
               
               # ex: /login login form for tracker application
               url(r'^login/$', auth_views.login, {'template_name': 'tracker/login.html'}),
               # ex: /logout clears current user session
               url(r'^log_out/$', views.log_out, name='log_out'),
               
               # ex: /place_order webpage for placing new orders
               url(r'^place_order/$', views.place_order, name='place_order'),
               # ex: /new_order accessible only from place_order.html creates a new order
               url(r'^new_order/$', views.new_order, name='new_order'),
               # ex: /view_orders renders orders_list.html and displays all current orders in system
               url(r'^view_orders/$', views.view_orders, name='view_orders'),
               # ex: /delete_order/1 deletes indicated order based on order number
               url(r'^delete_order/(?P<order_number>\d+)$', views.delete_order, name='delete_order'),
               # ex: /view_orders renders orders_list.html and displays all current orders in system
               url(r'^approve_order/(?P<order_number>\d+)$', views.approve_order, name='approve_order'),
               # ex: /order_print_form renders order_print_form.html and displays all current order in print format
               url(r'^order_print_form/(?P<order_number>\d+)$', views.order_print_form, name='order_print_form'),
               
               # ex: /app_settings/ renders app_settings.html and displays editable settings for application
               url(r'^app_settings/$', views.app_settings, name='app_settings'),
               # ex: /delete_email/exampleatex.com removes email from list of app alert recipients
               url(r'^delete_email/$', views.delete_email, name='delete_email'),
               # ex: /add_email adds indicated email to list of app alert recipients
               url(r'^add_email/$', views.add_email, name='add_email'),
               # ex: /add_email adds indicated label to list of inventory labels
               url(r'^add_label/$', views.add_label, name='add_label'),
               # ex: /delete_label deletes indicated label from list of inventory labels
               url(r'^delete_label/$', views.delete_label, name='delete_label'),
               ]

tracker/models.py
from __future__ import unicode_literals
import os, datetime
from django.db import models
from django.utils import timezone

def get_image_path(instance, filename):
    return os.path.join('photos', str(instance.id), filename)

class Product(models.Model):
    KG_TO_LBS_CONVERSION = 2.20462
    DEXTROSE = 'dex'
    GUM = 'gum'
    PANNED_SUGAR = 'psg'
    JAWBREAKER = 'jaw'
    CATEGORIES = ((DEXTROSE, 'Pressed Dextrose'),
                  (GUM, 'Bubble Gum'),
                  (PANNED_SUGAR, 'Panned Sugar'),
                  (JAWBREAKER, 'Jawbreaker'),)
    product_name = models.CharField(max_length=200)
    sm_lot_number = models.CharField(max_length=200)
    weight = models.DecimalField(max_digits=6, decimal_places=2)
    pieces = models.IntegerField()
    category = models.CharField(max_length=3,choices=CATEGORIES,default=DEXTROSE)
    popular = models.CharField(max_length=3,default='No')
    photo = models.FileField(upload_to=get_image_path, blank=True, null=True)
    #photo = models.ImageField(upload_to=get_image_path, blank=True, null=True)
    def get_pounds(self):
        return "{0:.2f}".format(Product.KG_TO_LBS_CONVERSION * float(self.weight))
    def __str__(self):
        return self.product_name
    # compares two product objects for equality based on product_name and sm_lot_number
    def __cmp__(self, other):
        return str(self.product_name) == str(other.product_name) and str(self.sm_lot_number) == str(other.sm_lot_number)

class Inventory(models.Model):
    INVENTORY_THRESHOLD = 50
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    add_date = models.DateTimeField('date added')
    lot_number = models.CharField(max_length=200)
    quantity = models.IntegerField(default=0)
    location = models.CharField(max_length=100)
    label = models.CharField(max_length=30, default='None')
    standard = models.CharField(max_length=3, default='Yes')
    dessicate = models.CharField(max_length=3, default='No')
    notes = models.CharField(max_length=200)
    alerts = models.IntegerField(default=0)
    def __str__(self):
        return self.product.product_name + " - " + str(self.lot_number) + " -quantity: " + str(self.quantity) + " -location: " + self.location
    # checks if inventory is empty
    def no_stock(self):
        if (self.quantity < 1):
            return True
        else:
            return False
    # checks quantity of inventory if less than 50 return critical is true, if product is popular threshold is 100
    def critical_stock(self):
        if (self.product.popular == 'Yes'):
            self.INVENTORY_THRESHOLD = 100
        if (self.quantity < self.INVENTORY_THRESHOLD):
            return True
        else:
            return False
    # changes alert value to prevent repeated alert messages
    def alert_sent(self, reset):
        self.alerts = 1
        if reset:
            self.alerts = 0

class Order(models.Model):
    PENDING = '0'
    APPROVED = '1'
    STATUS = ((PENDING, 'Pending'),
                  (APPROVED, 'Approved'),)
    order_number = models.IntegerField(default=1)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    date = models.DateTimeField('date')
    quantity = models.IntegerField(default=0)
    stock = models.CharField(max_length=100, default='')
    client = models.CharField(max_length=100)
    notes = models.CharField(max_length=200)
    status = models.CharField(max_length=1, choices=STATUS, default=PENDING)
    def __str__(self):
        return str(self.quantity) + " of " + self.product.product_name + " ordered by " + self.client + " on " + self.date.strftime("%D") + ". Additional Notes: " + self.notes
    # checks current status of order
    def is_approved(self):
        if self.status == Order.APPROVED:
            return True
        else:
            return False
    # alter the specified order from pending to approved and for associated pending stock objects
    def update_status(self):
        if self.status == Order.PENDING:
            self.status = Order.APPROVED
            for pstock in Pending_Stock.objects.all():
                if pstock.order_number == self.order_number:
                    pstock.status = self.status
            return True
        else:
            return False
    # returns a string based view of the stock field
    def get_stock(self):
        stocks = Pending_Stock.objects.all()
        inventories = []
        for stock in stocks:
            if stock.order_number == self.order_number:
                inventories.append("Lot Number: " + stock.inventory.lot_number + ", Quantity: " + str(stock.quantity))
        return inventories
    # checks order date to see if it's older than 7 days
    def order_age(self):
        date_order = self.date.strftime("%D").split("/")
        date_today = timezone.now().strftime("%D").split("/")
        date_difference = (int(date_today[0])*30 + int(date_today[1])) - (int(date_order[0])*30 + int(date_order[1]))
        if date_difference > 7 and self.get_status_display() == 'Pending':
            return True
        else:
            return False

class Pending_Stock(models.Model):
    order_number = models.IntegerField(default=1)
    inventory = models.ForeignKey(Inventory, on_delete=models.CASCADE)
    quantity = models.IntegerField(default=0)
    status = models.CharField(max_length=10, default='Pending')
    def __str__(self):
        return self.quantity + " from " + self.inventory.lot_number

class Email(models.Model):
    email = models.CharField(max_length=100, default='')

class Labels(models.Model):
    label = models.CharField(max_length=30, default='None')

tracker/templates/tracker/add_inventory.html
{% load staticfiles %}
<link rel="stylesheet" href="{% static 'tracker/css/style.css' %}">

<head>
    <ul id="menu-bar">
        <li>
            <a href="{% url 'tracker:index' %}">
                Inventory
            </a>
            <ul class="second-level-menu">
                <li>
                    <a href="{% url 'tracker:add_inventory' %}">
                        New Inventory
                    </a>
                </li>
            </ul>
        </li>
        <li>
            <a href="{% url 'tracker:view_orders' %}">
                Orders
            </a>
            <ul class="second-level-menu">
                <li>
                    <a href="{% url 'tracker:place_order' %}">
                        New Order
                    </a>
                </li>
            </ul>
        </li>
        <li>
            <a href="{% url 'tracker:view_products' %}">
                Products
            </a>
            <ul class="second-level-menu">
                <li>
                    <a href="{% url 'tracker:add_product' %}">
                        New Product
                    </a>
                </li>
            </ul>
        </li>
        <li>
            <a href="{% url 'tracker:log_out' %}">
                Logout
            </a>
        </li>
        <li id="settings">
            <a href="{% url 'tracker:app_settings' %}">
                <div id="img_holder"></div>
            </a>
        </li>
    </ul>
</head>

<body>
{% if error_message %}<h2 class="error">{{ error_message }}</h2>{% endif %}
{% if added %}<h2>Inventory successfully added.</h2>{% endif %}

<h1>New Inventory</h1>

<form action="{% url 'tracker:new_inventory' %}" method="post">
    {% csrf_token %}
    <label for="sm_lot_number" class="form">Product:</label>
    <select name="sm_lot_number" id="sm_lot_number" required>
        {% for product in product_list %}
            <option value="{{ product.sm_lot_number }}">{{ product }}</option>
        {% endfor %}
    </select><br />
    
    <label for="lot_number" class="form">Lot Number:</label>
    <input type="text" name="lot_number" id="lot_number" required/><br />
    
    <label for="quantity" class="form">Quantity:</label>
    <input type="text" name="quantity" id="quantity" required/><br />
    
    <label for="location" class="form">Location:</label>
    <input type="text" name="location" id="location" /required><br />
    
    <label for="label" class="form">Label:</label>
    <select name="label" id="label">
        <option value="none">None</option>
        {% for label in labels %}
        <option value="{{ label.label }}">{{ label.label }}</option>
        {% endfor %}
    </select><br /><br />
    
    <label for="standard" class="form">Standard:</label>
    <select name="standard" id="standard">
        <option value="No">No</option>
        <option value="Yes" selected="selected">Yes</option>
    </select><br /><br />
    
    <label for="dessicate" class="form">Dessicant:</label>
    <select name="dessicate" id="dessicate">
        <option value="No" selected="selected">No</option>
        <option value="Yes">Yes</option>
    </select><br /><br />
    
    <label for="notes" class="form">Notes:</label>
    <textarea name="notes" id="notes"></textarea><br /><br />
    
    <button class="add_button">Add Inventory</button>
</form>

<div class="spacer">
</div>

<footer>
    <p>Written by: Dan To, 2016</p>
    <a href="www.github.com/danhto">
        <img src="{% static "tracker/images/github.png" %}" />
    </a>
</footer>
</body>

tracker/templates/tracker/app_settings.html
{% load staticfiles %}
<link rel="stylesheet" href="{% static 'tracker/css/style.css' %}">
    
<head>
    <ul id="menu-bar">
        <li>
            <a href="{% url 'tracker:index' %}">
                Inventory
            </a>
            <ul class="second-level-menu">
                <li>
                    <a href="{% url 'tracker:add_inventory' %}">
                        New Inventory
                    </a>
                </li>
            </ul>
        </li>
        <li>
            <a href="{% url 'tracker:view_orders' %}">
                Orders
            </a>
            <ul class="second-level-menu">
                <li>
                    <a href="{% url 'tracker:place_order' %}">
                        New Order
                    </a>
                </li>
            </ul>
        </li>
        <li>
            <a href="{% url 'tracker:view_products' %}">
                Products
            </a>
            <ul class="second-level-menu">
                <li>
                    <a href="{% url 'tracker:add_product' %}">
                        New Product
                    </a>
                </li>
            </ul>
        </li>
        <li>
            <a href="{% url 'tracker:log_out' %}">
                Logout
            </a>
        </li>
        <li id="settings">
            <a href="">
                <div id="img_holder"></div>
            </a>
        </li>
    </ul>
</head>

<body>

{% if response %}
<h2 class="error">{{ response }}</h2>
{% endif %}

<h1>Settings</h1>

<form action="{% url 'tracker:delete_email' %}" enctype="multipart/form-data" method="post">
    {% csrf_token %}
    <label for="old_email" class="form">Current Alert Email Recipients:</label>
    <select name="old_email" id="old_email" />
    {% for email in emails %}
        <option value="{{ email.email }}">{{ email.email }}</option>
    {% endfor %}
    </select><br/>
    <button class="submit_button">Remove Email</button>
</form><br/><br/>

<form action="{% url 'tracker:add_email' %}" enctype="multipart/form-data" method="post">
    {% csrf_token %}
    <label for="new_email" class="form">Add Alert Email Recipient:</label>
    <input type="text" name="new_email" id="new_email" required/><br/>
    <button class="submit_button" name="add_email" id="add_email" />Add Email</button><br />
</form><br/>

<form action="{% url 'tracker:delete_label' %}" enctype="multipart/form-data" method="post">
    {% csrf_token %}
    <label for="del_label" class="form">Current Inventory Labels:</label>
    <select name="del_label" id="del_label" />
        <option value="none">None</option>
        {% for label in labels %}
        <option value="{{ label.label }}">{{ label.label }}</option>
        {% endfor %}
    </select><br/>
    <button class="submit_button">Remove Label</button>
</form><br/><br/>

<form action="{% url 'tracker:add_label' %}" enctype="multipart/form-data" method="post">
    {% csrf_token %}
    <label for="new_label" class="form">Add New Inventory Label:</label>
    <input type="text" name="new_label" id="new_label" required/><br/>
    <button class="submit_button" name="add_label" id="add_label" />Add Label</button><br />
</form><br/>

<div class="spacer">
</div>

<footer>
    <p>Written by: Dan To, 2016</p>
    <a href="www.github.com/danhto">
        <img src="{% static "tracker/images/github.png" %}" />
    </a>
</footer>
</body>

tracker/templates/tracker/orders_list.html
<meta http-equiv="refresh" content="30" />
{% load staticfiles %}
<link rel="stylesheet" href="{% static 'tracker/css/style.css' %}">
    
<head>
    <ul id="menu-bar">
        <li>
            <a href="{% url 'tracker:index' %}">
                Inventory
            </a>
            <ul class="second-level-menu">
                <li>
                    <a href="{% url 'tracker:add_inventory' %}">
                        New Inventory
                    </a>
                </li>
            </ul>
        </li>
        <li>
            <a href="{% url 'tracker:view_orders' %}">
                Orders
            </a>
            <ul class="second-level-menu">
                <li>
                    <a href="{% url 'tracker:place_order' %}">
                        New Order
                    </a>
                </li>
            </ul>
        </li>
        <li>
            <a href="{% url 'tracker:view_products' %}">
                Products
            </a>
            <ul class="second-level-menu">
                <li>
                    <a href="{% url 'tracker:add_product' %}">
                        New Product
                    </a>
                </li>
            </ul>
        </li>
        <li>
            <a href="{% url 'tracker:log_out' %}">
                Logout
            </a>
        </li>
        <li id="settings">
            <a href="{% url 'tracker:app_settings' %}">
                <div id="img_holder"></div>
            </a>
        </li>
    </ul>
</head>

<body>

{% if response %}
    <h2>{{ response }}</h2>
{% endif %}

<div id="pending_orders">
    <h1>Current Orders</h1>
    
    {% if orders %}
    <table>
        <tr>
            <th><a href="?order_by=order_number">Order Number</a></th>
            <th><a href="?order_by=product">Product Name</a></th>
            <th>Product Number</th>
            <th><a href="?order_by=date">Order Date</a></th>
            <th><a href="?order_by=quantity">Quantity</a></th>
            <th><a href="?order_by=client">Client</a></th>
            <th>Pending Stock</th>
            <th>Notes</th>
            <th>Status</th>
            <th></th>

        </tr>
        {% for order in orders %}
            {% if order.order_age %}
                <tr class="red">
            {% else %}
                <tr>
            {% endif %}
                <td class="data order_details">
                    <a href="{% url 'tracker:order_print_form' order.order_number %}">
                        {{ order.order_number }}
                    </a>
                </td>
                <td class="data order_details">
                    <a href="{% url 'tracker:order_print_form' order.order_number %}">
                        <span>
                            {{ order.product.product_name }}
                        </span>
                    </a>
                </td>
                <td class="data order_details">
                    <a href="{% url 'tracker:order_print_form' order.order_number %}">
                        {{ order.product.sm_lot_number }}
                    </a>
                </td>
                <td class="data order_details">
                    <a href="{% url 'tracker:order_print_form' order.order_number %}">
                        {{ order.date }}
                    </a>
                </td>
                <td class="data order_details">
                    <a href="{% url 'tracker:order_print_form' order.order_number %}">
                        {{ order.quantity }}
                    </a>
                </td>
                <td class="data order_details">
                    <a href="{% url 'tracker:order_print_form' order.order_number %}">
                        {{ order.client }}
                    </a>
                </td>
                <td class="data_stock">
                    <div class="stock_scroll_div">
                    {% for stock in order.get_stock %}
                        {{ stock }} </br>
                    {% endfor %}
                    </div>
                </td>
                <td class="data">{{ order.notes }}</td>
                {% if order.is_approved %}
                    <td class="approved_status">Approved</td>
                {% else %}
                    <td class="pending_status">
                        <form action="{% url 'tracker:approve_order' order.order_number %}" method="post">
                            {% csrf_token %}
                            Pending
                            <button class="approve_button">Approve</button>
                        </form>
                    </td>
                {% endif %}
                    <td class="tablebutton">
                        <form action="{% url 'tracker:delete_order' order.order_number %}" method="post">
                        {% csrf_token %}
                            <div id="delete_order">
                                <input type="submit" value="DEL" />
                            </div>
                        </form>
                    </td>
                </tr>
        </a>
        {% endfor %}
    </table>
    {% else %}
        <h2>No pending orders in system.</h2>
    {% endif %}
</div>

<div class="spacer">
</div>

<footer>
    <p>Written by: Dan To, 2016</p>
    <a href="www.github.com/danhto">
        <img src="{% static "tracker/images/github.png" %}" />
    </a>
</footer>
</body>

tracker/templates/tracker/product_inventory.html
{% load staticfiles %}
<link rel="stylesheet" href="{% static 'tracker/css/style.css' %}">

<head>
    <ul id="menu-bar">
        <li>
            <a href="{% url 'tracker:index' %}">
                Inventory
            </a>
            <ul class="second-level-menu">
                <li>
                    <a href="{% url 'tracker:add_inventory' %}">
                        New Inventory
                    </a>
                </li>
            </ul>
        </li>
        <li>
            <a href="{% url 'tracker:view_orders' %}">
                Orders
            </a>
            <ul class="second-level-menu">
                <li>
                    <a href="{% url 'tracker:place_order' %}">
                        New Order
                    </a>
                </li>
            </ul>
        </li>
        <li>
            <a href="{% url 'tracker:view_products' %}">
                Products
            </a>
            <ul class="second-level-menu">
                <li>
                    <a href="{% url 'tracker:add_product' %}">
                        New Product
                    </a>
                </li>
            </ul>
        </li>
        <li>
            <a href="{% url 'tracker:log_out' %}">
                Logout
            </a>
        </li>
        <li id="settings">
            <a href="{% url 'tracker:app_settings' %}">
                <div id="img_holder"></div>
            </a>
        </li>
    </ul>
</head>

<body>
    
{% if response %}
<h2>{{ response }}</h2>
{% endif %}

<h1>All inventory for {{ product_name }}</h1>
<table>
    <tr>
        <th>Lot Number</th>
        <th>Quantity</th>
        <th>Location</th>
        <th>Label</th>
        <th>Standard</th>
        <th>Dessicate</th>
        <th>Notes</th>
    </th>
    {% for inventory in inventory_list %}
    <tr>
        <td>{{ inventory.lot_number }}</td>
        <td class="update_quantity_cell" >
            <form action="{% url 'tracker:update_inventory' forloop.counter %}" method="post">
                {% csrf_token %}
                <input type="hidden" name="lot_number{{ forloop.counter }}" id="lot_number{{ forloop.counter }}" value="{{ inventory.lot_number }}" />
                <input type="hidden" name="sm_lot_number{{ forloop.counter }}" id="sm_lot_number{{ forloop.counter }}" value="{{ inventory.product.sm_lot_number }}" />
                <input type="text" name="quantity{{ forloop.counter }}" id="quantity{{ forloop.counter }}" value="{{ inventory.quantity }}" />
                <button class="submit_button">Update</button>
            </form>
        </td>
        <td>{{ inventory.location }}</td>
        <td>
            <form action="{% url 'tracker:update_inventory_label' forloop.counter %}" method="post">
                {% csrf_token %}
                <input type="hidden" name="lot_number{{ forloop.counter }}" id="lot_number{{ forloop.counter }}" value="{{ inventory.lot_number }}" />
                <input type="hidden" name="sm_lot_number{{ forloop.counter }}" id="sm_lot_number{{ forloop.counter }}" value="{{ inventory.product.sm_lot_number }}" />
                <select name="label{{ forloop.counter }}" id="label{{ forloop.counter }}">
                    <option value="none">None</option>
                    {% for label in labels %}
                        {% if label.label == inventory.label %}
                            <option value="{{ label.label }}" selected>{{ label.label }}</option>
                        {% else %}
                            <option value="{{ label.label }}">{{ label.label }}</option>
                        {% endif %}
                    {% endfor %}
                </select>
                <button class="submit_button">Change</button>
            </form>
        </td>
        <td>{{ inventory.standard }}</td>
        <td>{{ inventory.dessicate }}</td>
        <td>{{ inventory.notes }}</td>
    </tr>
    {% endfor %}
</table>

<div class="spacer">
</div>

<footer>
    <p>Written by: Dan To, 2016</p>
    <a href="www.github.com/danhto">
        <img src="{% static "tracker/images/github.png" %}" />
    </a>
</footer>
</body>

tracker/templates/tracker/product_list.html
{% load staticfiles %}
<link rel="stylesheet" href="{% static 'tracker/css/style.css' %}">
    
<head>
    <ul id="menu-bar">
        <li>
            <a href="{% url 'tracker:index' %}">
                Inventory
            </a>
            <ul class="second-level-menu">
                <li>
                    <a href="{% url 'tracker:add_inventory' %}">
                        New Inventory
                    </a>
                </li>
            </ul>
        </li>
        <li>
            <a href="{% url 'tracker:view_orders' %}">
                Orders
            </a>
            <ul class="second-level-menu">
                <li>
                    <a href="{% url 'tracker:place_order' %}">
                        New Order
                    </a>
                </li>
            </ul>
        </li>
        <li>
            <a href="{% url 'tracker:view_products' %}">
                Products
            </a>
            <ul class="second-level-menu">
                <li>
                    <a href="{% url 'tracker:add_product' %}">
                        New Product
                    </a>
                </li>
            </ul>
        </li>
        <li>
            <a href="{% url 'tracker:log_out' %}">
                Logout
            </a>
        </li>
        <li id="settings">
            <a href="{% url 'tracker:app_settings' %}">
                <div id="img_holder"></div>
            </a>
        </li>
    </ul>
</head>

<body>

<h1>Existing Products</h1>

{% if product_list %}
<form action="{% url 'tracker:view_products' %}" method="POST">
    {% csrf_token %}
    <select name="filtcategory" id="filtcategory">
        <option value="" >All</option>
        {% for key, value in categories.items %}
        {% if filter == key %}
        <option value="{{ key }}" selected>{{ value }}</option>
        {% else %}
        <option value="{{ key }}" >{{ value }}</option>
        {% endif %}
        {% endfor %}
    </select>
    <input type="submit" value="Filter" />
</form>

<table class="product_table">
    <tr>
        <th>Product Name</th>
        <th>Product Lot Number</th>
        <th class="delete_button"></th>
    </tr>
    
    {% for product in product_list %}
    <tr class="product_row">
        <td class="product_details">
            <a href="{% url 'tracker:product_details' product.sm_lot_number %}">
                {{ product.product_name }}
            </a>
        </td>
        <td class="product_details">
            <a href="{% url 'tracker:product_details' product.sm_lot_number %}">
                {{ product.sm_lot_number }}
            </a>
        </td>
        <td class="delete_button">
            <form action="{% url 'tracker:delete_product' product.sm_lot_number %}" method="POST">
                {% csrf_token %}
                <button class="table_delete_button" type="submit">Delete</button>
            </form>
        </td>
    <tr>
    {% endfor %}
</table>
{% else %}
<h2>There are no products currently in the system.</h2>
{% endif %}

<div class="spacer">
</div>

<footer>
    <p>Written by: Dan To, 2016</p>
    <a href="www.github.com/danhto">
        <img src="{% static "tracker/images/github.png" %}" />
    </a>
</footer>
</body>